import type { Metadata } from 'next';

export const SITE_URL = 'https://aiot-camp-web.vercel.app';
export const SITE_NAME = '未來科技啟航：AIoT 推廣科學營';
export const HOME_TITLE = `${SITE_NAME}｜國立臺北教育大學`;
export const HOME_DESCRIPTION =
  '國立臺北教育大學執行之國科會大眾科學教育計畫，以生活情境與動手實作，帶國小學生認識 AI 與物聯網（AIoT），完成智慧牙刷、姿勢辨識、智慧家庭等作品。';

// Generated by app/opengraph-image.tsx; resolved to an absolute URL via metadataBase.
const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  type: 'image/png',
  alt: `${SITE_NAME}｜國科會大眾科學教育計畫｜國立臺北教育大學`,
};

export const sitePaths =['/', '/about', '/learn', '/hands-on', '/programs', '/news', '/contact'] as const;

type PageSeo = {
  title: string;
  description: string;
  path: (typeof sitePaths)[number];
};

// Metadata objects are shallowly merged across segments, so each page
// returns complete openGraph/twitter objects instead of relying on the layout.
export function pageMetadata({ title, description, path }: PageSeo): Metadata {
  const isHome = path === '/';
  const fullTitle = isHome ? HOME_TITLE : `${title}｜${SITE_NAME}`;

  return {
    title: isHome ? { absolute: HOME_TITLE } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title: fullTitle,
      description,
      url: path,
      type: 'website',
      siteName: SITE_NAME,
      locale: 'zh_TW',
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [OG_IMAGE],
    },
  };
}
